import { getCSPRClickPublicConfig } from "./csprclick-browser";

export function getCSPRClickClientPublicConfig() {
  return getCSPRClickPublicConfig({
    NEXT_PUBLIC_CASPER_CHAIN_NAME: process.env.NEXT_PUBLIC_CASPER_CHAIN_NAME,
    NEXT_PUBLIC_CSPR_CLICK_APP_ID: process.env.NEXT_PUBLIC_CSPR_CLICK_APP_ID,
    NEXT_PUBLIC_CSPR_CLICK_APP_NAME: process.env.NEXT_PUBLIC_CSPR_CLICK_APP_NAME,
    NEXT_PUBLIC_CSPR_CLICK_CONTENT_MODE: process.env.NEXT_PUBLIC_CSPR_CLICK_CONTENT_MODE,
    NEXT_PUBLIC_CSPR_CLICK_PROVIDERS: process.env.NEXT_PUBLIC_CSPR_CLICK_PROVIDERS,
    NEXT_PUBLIC_CSPR_CLICK_ROOT_ELEMENT: process.env.NEXT_PUBLIC_CSPR_CLICK_ROOT_ELEMENT,
    NEXT_PUBLIC_CSPR_CLICK_UI_CONTAINER: process.env.NEXT_PUBLIC_CSPR_CLICK_UI_CONTAINER,
  });
}
