import type { AuditEvent, Receipt, Tool, WalletProfile } from "./types";

export const tools: Tool[] = [
  {
    id: "get_cspr_quote",
    description: "CSPR/WCSPR trade quote",
    target: "GET /v1/quote",
    price: 0.05,
    enabled: true,
    published: true,
    provider: "Make Software Labs",
  },
  {
    id: "get_market_depth",
    description: "Bid/ask depth ladder",
    target: "GET /v1/depth",
    price: 0.1,
    enabled: true,
    published: false,
    provider: "Make Software Labs",
  },
  {
    id: "list_pairs",
    description: "Tradable pairs",
    target: "GET /v1/pairs",
    price: null,
    enabled: false,
    published: false,
    provider: "Make Software Labs",
  },
];

export const wallets: WalletProfile[] = [
  {
    id: "agent-trader-01",
    account: "0x9f3a...b2c1",
    fullAccount: "account-hash-9f3a0000000000000000000000000000000000000000000000000000000000b2c1",
    network: "casper:casper-test",
    signingMode: "Hosted encrypted signer",
    balance: "12.50",
    status: "ready fixture",
    funded: true,
  },
  {
    id: "research-readonly",
    account: "0x71c8...0a4f",
    fullAccount: "account-hash-71c8000000000000000000000000000000000000000000000000000000000a4f",
    network: "casper:casper-test",
    signingMode: "View-only signer",
    balance: "unavailable",
    status: "funding pending",
    funded: false,
  },
];

export const receipts: Receipt[] = [
  {
    id: "rcp_8f42a1",
    time: "14:22:07",
    provider: "Make Software Labs",
    tool: "get_cspr_quote",
    wallet: "agent-trader-01",
    amount: "0.05",
    asset: "WCSPR",
    status: "raw_proof_unavailable",
    hash: null,
    client: "cursor-mcp-01",
    reason: "Design fixture only: no real Casper Testnet deploy hash has been produced yet.",
  },
  {
    id: "rcp_8f4290",
    time: "14:19:51",
    provider: "Weather Risk Desk",
    tool: "get_weather_risk",
    wallet: "agent-trader-01",
    amount: "0.10",
    asset: "WCSPR",
    status: "blocked",
    hash: null,
    client: "cursor-mcp-01",
    reason: "Exceeds max-per-call (0.10 > policy 0.08 WCSPR)",
  },
  {
    id: "rcp_8f4271",
    time: "13:58:02",
    provider: "Make Software Labs",
    tool: "get_cspr_quote",
    wallet: "research-readonly",
    amount: "0.05",
    asset: "WCSPR",
    status: "settle_failed",
    hash: null,
    client: "custom-agent",
    reason: "Facilitator settle returned insufficient CEP-18 allowance",
  },
  {
    id: "rcp_8f4255",
    time: "13:22:47",
    provider: "Make Software Labs",
    tool: "get_cspr_quote",
    wallet: "agent-trader-01",
    amount: "0.05",
    asset: "WCSPR",
    status: "verify_failed",
    hash: null,
    client: "custom-agent",
    reason: "Payment payload signature did not verify at facilitator",
  },
  {
    id: "rcp_8f4241",
    time: "12:54:10",
    provider: "Weather Risk Desk",
    tool: "get_weather_risk",
    wallet: "agent-trader-01",
    amount: "0.08",
    asset: "WCSPR",
    status: "upstream_failed",
    hash: null,
    client: "cursor-mcp-01",
    reason: "Provider upstream API returned 502 after authorization - settlement withheld",
  },
  {
    id: "rcp_8f4230",
    time: "12:31:55",
    provider: "Make Software Labs",
    tool: "get_cspr_quote",
    wallet: "research-readonly",
    amount: "0.05",
    asset: "WCSPR",
    status: "auth_failed",
    hash: null,
    client: "custom-agent",
    reason: "MCP client bearer token expired before policy/payment",
  },
];

export const auditEvents: AuditEvent[] = [
  { time: "14:22:07", label: "Proof pending fixture recorded", meta: "rcp_8f42a1 - no deploy hash claimed", kind: "warn" },
  { time: "14:19:51", label: "Spend blocked by policy", meta: "get_weather_risk - 0.10 > 0.08", kind: "block" },
  { time: "13:58:02", label: "Settlement failed", meta: "rcp_8f4271 - CEP-18 allowance", kind: "fail" },
  { time: "13:31:14", label: "Policy changed", meta: "agent-trader-01 - max-per-call", kind: "info" },
  { time: "12:40:08", label: "Endpoint published", meta: "/mcp/make-software", kind: "ok" },
  { time: "12:18:33", label: "Tool priced", meta: "get_cspr_quote - 0.05 WCSPR", kind: "info" },
  { time: "11:52:19", label: "Credentials changed", meta: "x-api-key - Make Software Labs", kind: "warn" },
  { time: "11:30:02", label: "Source created", meta: "CSPR Trade Quote - OpenAPI", kind: "info" },
];

export const consoleReceiptId = "rcp_8f42a1";
